CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL,
	first_name VARCHAR (225) NOT NULL
);

CREATE TABLE exercises (
	id int NOT NULL,
	title varchar(255) NOT NULL,
	description varchar(255) NULL,
	is_arms int NOT NULL DEFAULT 0,
	is_legs int NOT NULL DEFAULT 0,
	is_back int NOT NULL DEFAULT 0,
	is_chest int NOT NULL DEFAULT 0,
	is_core int NOT NULL DEFAULT 0,
	is_cardio int NOT NULL DEFAULT 0,
	is_advanced int NOT NULL DEFAULT 0
);

CREATE TABLE workouts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    workouts_name VARCHAR (255) NOT NULL,
	total_length int NOT NULL DEFAULT 0
);

CREATE TABLE workout_details (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workouts_id INTEGER REFERENCES workouts(id) ON DELETE CASCADE NOT NULL,
	exercises_id INTEGER REFERENCES exercises(id) ON DELETE CASCADE NOT NULL,
	exercise_reps int NOT NULL DEFAULT 1
);

INSERT INTO public.users ("email", "password", "first_name") VALUES 
('admin@gmail.com','Admin123', 'Bob'),
('user@gmail.com','User123', 'Bill');
